// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmclhojfyfkqnxkbkhio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtY2xob2pmeWZrcW54a2JraGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODk0NDEsImV4cCI6MjA3MDE2NTQ0MX0.ook8QBq2sTZt30QXoZaaTYCjN-0ThRtPq9-9fr-YCZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});